base_config: configs/kitti/kitti.yaml

exp_name: kitti/sequence00



data_specs:
  data_path: '/home/robotics/Data/KITTI/sequences/00'
  use_gt: True
  max_depth: 40
  min_depth: 5

tracker_specs:
  start_frame: 0
  end_frame: 1
  read_offset: 1